In [1]:
!pip install numpy

zsh:1: /Users/isha/Documents/NLP/.venv/bin/pip: bad interpreter: /Users/isha/Documents/NLP/venv/.venv/bin/python3.14: no such file or directory


In [2]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 729.4 kB/s  0:00:06 eta 0:00:01

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

array = np.array([1, 2, 3, 4, 5,6])
print(array)

[1 2 3 4 5 6]


In [9]:
# converted to 2D array
arr = array.reshape(2,3) 

In [ ]:
# used ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
print("Array: ",arr) #to print arrays
print("Shape: ", arr.shape) #to print shape of array
print("number of dimensions: ", arr.ndim) #to print number of dimensions
print("Number of elements: ", arr.size) #to print number of elements
print("Data type:", arr.dtype) #to print data type of array
print("Size of each element in bytes: ", arr.itemsize) #to print size of each element in bytes

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
number of dimensions:  2
Number of elements:  6
Data type: int64
Size of each element in bytes:  8


In [ ]:
# numpy vactorised operation
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# elementwise addition
print("Sum: ", arr1+arr2)

# elemenwise subtraction
print("subs: ", arr2 - arr1)

# similarly we can do / and *

Sum:  [5 7 9]
subs:  [3 3 3]


In [21]:
# universal functions
arr = np.array([2,3,4])
print("Square root: ", np.sqrt(arr))
print("Exponential: ", np.exp(arr))
print("Sine: ", np.sin(arr))
print("Natural log:", np.log(arr))


Square root:  [1.41421356 1.73205081 2.        ]
Exponential:  [ 7.3890561  20.08553692 54.59815003]
Sine:  [ 0.90929743  0.14112001 -0.7568025 ]
Natural log: [0.69314718 1.09861229 1.38629436]


In [26]:
arr = np.array([[1,2,3,6],[4,5,6,4],[7,8,9,7]])
print(arr)

[[1 2 3 6]
 [4 5 6 4]
 [7 8 9 7]]


In [27]:
# to fetch perticular element
print(arr[0,1]) # element at 0th row and 1st column

2


In [28]:
# if we want to fetch 2nd row and 3rd column
print(arr[1:,2:]) # 1: means from 1st row to end and 2: means from 2nd column to end

[[6 4]
 [9 7]]


In [29]:
# modify aray element
arr[0,0] = 100
print(arr)

[[100   2   3   6]
 [  4   5   6   4]
 [  7   8   9   7]]


In [33]:
# statistical concept - normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# calculating mean and standard daviation
mean = np.mean(data)
std =  np.std(data)

print("Mean: ", mean)
print("standard deviation: ", std)

# normalize the data
normalized_data = (data - mean) / std
print("Normalized data: ", normalized_data)

# variance
variance = np.var(data)
print("Variance: ", variance)

# median
median = np.median(data)
print("median: ", median)

Mean:  3.0
standard deviation:  1.4142135623730951
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance:  2.0
median:  3.0


In [35]:
data = np.array([1,2,3,4,5])

data>3
data[data>3]

array([4, 5])